### ISSUE TITLE
Unexpected response format

### ISSUE THREAD

**Issue by cmeltt** [VolkanSah/GPT-API-Integration-in-HTML-CSS-with-JS-PHP#18]
Hello, thank you for the code.
As the gpt4 API is now available for all I tried to use your code with my API key but I have this error in the log console:
Object
error
: 
{message: 'you must provide a model parameter', type: 'invalid_request_error', param: null, code: null}
[[Prototype]]
: 
Object

I tried to use gpt-4, gpt-3.5-turbo and so one but alsways the same message.
Can you help me please ?

**Comment by VolkanSah** [comment]
Dear User,

I appreciate your interest in my project and understand that you're experiencing difficulties. However, it's important to note that a substantial part of using and learning from open source projects is self-reliance and thorough reading of provided documentation.

In this case, both the README and comments in the code explicitly address the issue you're facing. I urge you to spend some more time familiarizing yourself with the materials already provided. A key part of becoming proficient in any technical field is self-guided learning and problem solving.

Please, review the existing documents and closed issues, as they already contain extensive explanations and solutions to common problems, including the one you've mentioned. If you're still having issues after thoroughly reviewing these resources, feel free to post a new, detailed description of the issue you're experiencing, and I'd be more than happy to help.

Remember, part of joining the developer community is respecting the effort and time of others. If you find this project or any other helpful, consider showing your appreciation through stars or contributions. It's a small action, but it goes a long way in encouraging maintainers to continue sharing their work.

Volkan Sah
